name: dep
description: Dep

inputs:
  environment:
    description: 'The environment target'
    required: true
  bucket:
    description: "The AWS S3 Bucket's name selected as destination"
    required: true
  cloudfront_distribution_id:
    description: 'The ID of the Cloudfront distribution to invalidate'
    required: true
  cdn_path:
    description: 'The CDN bucket S3 URL'
    required: false

runs:
  using: "composite"
  steps:
    
    - name: Build static website
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        CDN_PATH: ${{ inputs.cdn_path }}
      shell: bash
      run: echo "$CDN_PATH"

    - name: Deploy to S3 Bucket
      shell: bash
      run: run: echo "${{ inputs.bucket }}"

    - name: Create AWS Cloudfront Invalidation
      shell: bash
      run: echo "${{ inputs.cloudfront_distribution_id }}"
