name: dep
description: Dep

inputs:
  environment:
    description: 'The environment target'
    required: true
  bucket:
    description: "The AWS S3 Bucket's name selected as destination"
    required: true
  cloudfront_distribution_id:
    description: 'The ID of the Cloudfront distribution to invalidate'
    required: true
  cdn_path:
    description: 'The CDN bucket S3 URL'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    
    - name: Build static website
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        CDN_PATH: ${{ inputs.cdn_path }}
      shell: bash
      run: echo "$CDN_PATH"

    - name: Deploy to S3 Bucket
      env:
        BUCKET: ${{ inputs.bucket }}
      shell: bash
      run: run: echo "${{ inputs.environment }}"

    - name: Create AWS Cloudfront Invalidation
      env:
        CDN: ${{ inputs.cloudfront_distribution_id }}
      shell: bash
      run: echo "$CDN"
