version: "3"

services:
  app:
    build:
      context: ./app
    container_name: strapi_v4_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: adminpassword
    volumes:
      - ./app:/srv/app
    ports:
      - 127.0.0.1:8000:1337
    depends_on:
      - db

  db:
    image: postgres:14.6
    container_name: strapi_v4_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - ./data:/var/lib/postgresql/data