name: test var
on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'The tenant inherent to the site'
        type: string
        required: true

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  manual_deploy:
    name: manual trigger
    #if: github.event_name == 'workflow_dispatch'
    runs-on: 'ubuntu-latest'

    steps:
    
      - name: Mostra evento
        run: echo "${{ github.event_name }}"

      - name: Mostra Tenant Input
        run: echo "${{ inputs.tenant }}"
    
      - name: Set Variabile CDN1
        id: set-value-cdn1
        run: echo "cnd_url=$(if [[ "${{ inputs.tenant }}" == "send" ]]; then echo "${{ vars.CDN_PATH_A }}"; elif [[ "${{ inputs.tenant }}" == "appio" ]]; then echo "${{ vars.CDN_PATH_B }}"; else echo "Tenant non valido";fi )" >> $GITHUB_ENV
    
      - name: Set Variabile CDN2
        id: set-value-cdn2
        run: |
          if [[ "${{ inputs.tenant }}" == "send" ]]; then
            echo "Valore di CDN_URL: ${{ vars.CDN_PATH_A }}"
          elif [[ "${{ inputs.tenant }}" == "appio" ]]; then
            echo "Valore di CDN_URL: ${{ vars.CDN_PATH_B }}"
          else
            echo "TENANT non valido"
          fi

      - name: Mostra CDN Path
        run: echo ${{ steps.set-value-cdn1.outputs.cnd_url }}
        #with:
          #  go-version: ${{ steps.vars.outputs.go_version }}
        

