name: test var
on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'The tenant inherent to the site'
        type: string
        required: true

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  manual_deploy:
    strategy:
      matrix:
        tenant: [${{ inputs.tenant }}]
        cdn_tenant: [${{ vars.CDN_PATH_$tenant }}]
     #   include:
     #     - tenant:  ${{ inputs.tenant }}
      #      cdnvar: vars.CDN_PATH_$tenant
     #       cdn_path: ${{ matrix.include.cdnvar }}
    name: manual trigger
    if: github.event_name == 'workflow_dispatch'
    runs-on: 'ubuntu-latest'

    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      - name: Utilizza il valore estratto
        run: echo "Il valore della variabile di contesto è ${{ matrix.cdn_tenant }}"

      - name: iff
        if: ${{ github.event.inputs.tenant == 'A' }}
        run: echo "Il valore della variabile di contesto è ${{vars.CDN_PATH_A }}"

      - name: Set Variabile CDN
        run: |
          if [[ "${{ inputs.tenant }}" == "A" ]]; then
            echo "Valore di CDN_URL: ${{ vars.CDN_PATH_A }}"
          elif [[ "${{ inputs.tenant }}" == "B" ]]; then
            echo "Valore di CDN_URL: ${{ vars.CDN_PATH_B }}"
          else
            echo "TENANT non valido"
          fi
        

